### ISSUE TITLE
ENTREVISTA

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-yce#1]
[Reporte de entrevista Ingeniero de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-yce/files/12567576/Reporte.de.entrevista.Ingeniero.de.Software.pdf)

**Comment by Luz1727** [comment]
Calificacion 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
